version: '3.7'

services:
  bun-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src  # Mapeando o diretório src no host para /app/src no contêiner
